package(
    default_visibility = [
        "//magenta/tools/pip:__subpackages__",
        "//magenta/models/nsynth:__subpackages__",
    ],
)


py_library(
    name = "utils",
    srcs = ["utils.py"],
    deps = [
        # librosa dep
        # numpy dep
        # tensorflow dep
        # scipy dep
    ],
)

py_library(
    name = "reader",
    srcs = ["reader.py"],
    deps = [
        ":utils",
        # numpy dep
        # tensorflow dep
   ],
)
