"""Serves an HTML page for labeling the k-means clusters.

Takes cluster TFRecords generated by `staffline_patches_kmeans_pipeline.py` and
serves an HTML page containing cluster images. When the HTML form containing
labels is submitted, it (by defaults) overwrites the clusters file, adding the
labels.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# internal imports
from absl import flags
import numpy as np
from six.moves import BaseHTTPServer
import tensorflow as tf

from magenta.models.omr.training.clustering import kmeans_labeler_request_handler as handler

from tensorflow.python.lib.io import tf_record

FLAGS = flags.FLAGS

flags.DEFINE_string('clusters_path', None, 'Path to the input patch TFRecords')
flags.DEFINE_string('output_path', None,
                    'Path to the output patch TFRecords. Defaults to '
                    'overwriting clusters_path.')
flags.DEFINE_integer('port', 8000, 'Port for serving the labeler.')


def load_clusters(input_path):
  """Loads TFRecords of Examples representing the k-means clusters.

  Examples are typically the output of `staffline_patches_kmeans_pipeline.py`.

  Args:
    input_path: Path to the TFRecords of Examples.

  Returns:
    A NumPy array of shape (num_clusters, patch_height, patch_width).
  """

  def parse_example(example_str):
    example = tf.train.Example()
    example.ParseFromString(example_str)
    height = example.features.feature['height'].int64_list.value[0]
    width = example.features.feature['width'].int64_list.value[0]
    return np.asarray(
        example.features.feature['features'].float_list.value).reshape((height,
                                                                        width))

  return np.asarray([
      parse_example(example)
      for example in tf_record.tf_record_iterator(input_path)
  ])


def main(_):
  server_address = ('localhost', FLAGS.port)
  clusters = load_clusters(FLAGS.clusters_path)
  # Default to overwriting the input.
  output_path = FLAGS.output_path or FLAGS.clusters_path

  def create_request_handler(*args):
    return handler.LabelerHTTPRequestHandler(clusters, output_path, *args)

  server = BaseHTTPServer.HTTPServer(server_address, create_request_handler)
  print('Listening on port %d...', FLAGS.port)
  server.serve_forever()


if __name__ == '__main__':
  tf.app.run()
